import Navbar from "@/components/common/navbar/navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="lg:mt-28 mt-20">
      <Navbar></Navbar>
      {children}
    </main>
  );
}
